// Heuristic detection of generated files (codegen clients, snapshots, bundled
// output). These deny for a different reason than "too big": nobody needs to
// understand them, only grep inside them, so delegating to bulk-reader is
// wasted work even if the size gate would otherwise send it there.
const fs = require("fs");

const MARKERS = [/@generated\b/, /DO NOT EDIT/, /Code generated by/i];
const HEAD_BYTES = 4096;
const HEAD_LINES = 20;

function looksGenerated(text) {
  if (!text) return false;
  const head = text.split("\n").slice(0, HEAD_LINES).join("\n");
  return MARKERS.some((re) => re.test(head));
}

// Cheap partial read for the byte-size fast path, where the full file is
// never read (that's the whole point of the fast path).
function readHead(filePath, maxBytes = HEAD_BYTES) {
  let fd;
  try {
    fd = fs.openSync(filePath, "r");
    const buf = Buffer.alloc(maxBytes);
    const bytesRead = fs.readSync(fd, buf, 0, maxBytes, 0);
    return buf.toString("utf8", 0, bytesRead);
  } catch {
    return "";
  } finally {
    if (fd !== undefined) {
      try {
        fs.closeSync(fd);
      } catch {
        // ignore
      }
    }
  }
}

module.exports = { looksGenerated, readHead, MARKERS };
